program make_folders
    
    // Create folders if they don't exist
    cap mkdir "../data/"
    cap mkdir "../data/EMinput"
    cap mkdir "../data/EMinput/modified"
	cap mkdir "../data/EMinput/original"
	//cap mkdir "../data/EMinput/original/UDBs"
	//cap mkdir "../data/EMinput/other"
    cap mkdir "../data/EMoutput"
    cap mkdir "../data/EMoutput/modified"
    cap mkdir "../data/baseline"
    cap mkdir "../data/emsim"
    cap mkdir "../data/LSscenarios"
    cap mkdir "../data/LSscenarios/0_fullsample"
    cap mkdir "../data/LSscenarios/1_counterfactuals"
    cap mkdir "../data/LSscenarios/2_postEM_appended"
    cap mkdir "../data/LSscenarios/3_LS"
    cap mkdir "../data/LSscenarios/4_pred"
    cap mkdir "../data/LSscenarios/5_bootstrap"
    cap mkdir "../data/LSscenarios/7_aggregate"
    cap mkdir "../data/LSscenarios/8_reduced"
    cap mkdir "../data/LSscenarios/9_emtr"
    cap mkdir "../data/bootstrap_weights"
    cap mkdir "../data/results"
    cap mkdir "../data/results/estimation"
    cap mkdir "../data/results/heckman"
    cap mkdir "../data/results/elasticities"
    cap mkdir "../data/results/hhsample"
    cap mkdir "../data/results/mitr"
    cap mkdir "../data/results/implied_eti"
    cap mkdir "../data/results/population"
    cap mkdir "../data/results/population/scalars"
	cap mkdir "../data/results/behaviour"
	cap mkdir "../results"
	cap mkdir "../log/"
    /*cap mkdir "../graphs"
    cap mkdir "../graphs/elasticities"
    cap mkdir "../graphs/lhw"
    cap mkdir "../graphs/fit"
    cap mkdir "../graphs/implied_eti"
    cap mkdir "../graphs/mitr"
    cap mkdir "../config/" 
    cap mkdir "../log/EM_errlog"
    cap mkdir "../log/elasticities"
    cap mkdir "../log/vars"
    cap mkdir "../log/flex_sample"
    cap mkdir "../log/wage_pred"
    cap mkdir "../log/lhw"
    cap mkdir "../log/heckman"
    cap mkdir "../log/lslogit"
    cap mkdir "../log/fit"
    cap mkdir "../log/bootstrap"
    cap mkdir "../log/mitr"*/
    //cap mkdir "../tables/"
    //cap mkdir "../euromod/"

end
